[package]
name = "gm_rant"
version = "1.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.75"
gmod = {version = "*", features = ["gmcl"], default-features = false}
once_cell = "1.18.0"
rant = "4.0.0-alpha.33"
