name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - run: rustup default nightly
    - run: rustup target add i686-pc-windows-msvc
    - name: Build
      run: cargo build -r --verbose

    - name: Move output
      run: |
        cp target/release/gm_rant.dll gmsv_rant_win64.dll
        cp target/release/gm_rant.dll gmcl_rant_win64.dll
        
    - name: Build x32
      run: cargo build -r --verbose --target i686-pc-windows-msvc
      
    - name: Move output
      run: |
        cp target/release/gm_rant.dll gmsv_rant_win32.dll
        cp target/release/gm_rant.dll gmcl_rant_win32.dll

    - uses: actions/upload-artifact@v3
      with:
        name: Windows
        path: |
          ./*.dll

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: rustup default nightly
    - run: rustup target add i686-unknown-linux-gnu
    - run: sudo apt-get update && sudo apt-get install -y gcc-multilib g++-multilib
    - name: Build
      run: cargo build -r --verbose

    - name: Move output
      run: |
        cp target/release/libgm_rant.so gmsv_rant_linux64.dll
        cp target/release/libgm_rant.so gmcl_rant_linux64.dll
        
    - name: Build x32
      run: cargo build -r --verbose --target i686-unknown-linux-gnu
      
    - name: Move output
      run: |
        cp target/release/libgm_rant.so gmsv_rant_linux.dll
        cp target/release/libgm_rant.so gmcl_rant_linux.dll

    - uses: actions/upload-artifact@v3
      with:
        name: Linux
        path: |
          ./*.dll

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - run: rustup default nightly
    - name: Build
      run: cargo build -r --verbose

    - name: Move output
      run: |
        cp target/release/libgm_rant.dylib gmsv_rant_osx64.dll
        cp target/release/libgm_rant.dylib gmcl_rant_osx64.dll

    - uses: actions/upload-artifact@v3
      with:
        name: OSX
        path: |
          ./*.dll