name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build -r --verbose

    - name: Move output
      run: |
        cp target/release/gm_rant.so gmsv_rant_linux64.dll
        cp target/release/gm_rant.so gmcl_rant_linux64.dll
        
    - name: Build x32
      run: cargo build -r --verbose --target i686-unknown-linux-gnu
      
    - name: Move output
      run: |
        cp target/release/gm_rant.so gmsv_rant_linux.dll
        cp target/release/gm_rant.so gmcl_rant_linux.dll
